### Mycobank Parser

In [3]:
import pandas as pd
import numpy as np
import sys

In [5]:
MBList = (r'MBList2025.xlsx')
MBist_df = pd.read_excel(MBList, index_col=None)
MBList_df = MBist_df.rename(columns={"ID": "id", "Taxon name": "name"}, inplace=True)
MBist_df.set_index('id', inplace=True)
MBist_df

,name,Authors,Rank.Rank name,Year of effective publication,Name status,MycoBank #,Hyperlink,Classification,Current name.Taxon name,Synonymy
id,,,,,,,,,,
541217,Aabaarnia,Diederich,gen.,2014,Legitimate,810083,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Ascomycota, Pezizomycotina, Le...",-,"Current name: Aabaarnia Diederich, Bull. Soc. ..."
541218,Aabaarnia siphulicola,Diederich,sp.,2014,Legitimate,810084,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Ascomycota, Pezizomycotina, Le...",Aabaarnia siphulicola,"Current name: Aabaarnia siphulicola Diederich,..."
56001,Aaosphaeria,Aptroot,gen.,1995,Legitimate,6184,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Ascomycota, Pezizomycotina, Do...",Aaosphaeria,"Current name: Aaosphaeria Aptroot, Nova Hedwig..."
47088,Aaosphaeria arxii,(Aa) Aptroot,sp.,1995,Legitimate,412366,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Ascomycota, Pezizomycotina, Do...",Aaosphaeria arxii,"Current name: Aaosphaeria arxii (Aa) Aptroot, ..."
594682,Aaosphaeria pasadenensis,K. Venkateswaran & A.M. Chander,-,2022,Legitimate,844547,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Ascomycota, Pezizomycotina, Do...",-,Current name: Aaosphaeria pasadenensis Venkate...
...,...,...,...,...,...,...,...,...,...,...
594790,Zyzygomyces leucodermiae,"Diederich, Millanes, Ertz, Etayo & Flakus",-,2022,Legitimate,844621,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Basidiomycota, Agaricomycotina...",-,Current name: Zyzygomyces leucodermiae Diederi...
594791,Zyzygomyces mobergii,Diederich & Millanes,-,2022,Legitimate,844622,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Basidiomycota, Agaricomycotina...",-,Current name: Zyzygomyces mobergii Diederich &...
594792,Zyzygomyces physciacearum,"(Diederich) Diederich, Millanes & Wedin",-,2022,Legitimate,844623,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Basidiomycota, Agaricomycotina...",-,Current name: Zyzygomyces physciacearum (Diede...
594793,Zyzygomyces physconiae,"Diederich, Millanes, P. Pinault & Brackel",-,2022,Legitimate,844624,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Basidiomycota, Agaricomycotina...",-,Current name: Zyzygomyces physconiae Diederich...
594794,Zyzygomyces polyblastidii,"Diederich, Flakus, Etayo & Rodriguez Flakus",-,2022,Legitimate,844625,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Basidiomycota, Agaricomycotina...",-,Current name: Zyzygomyces polyblastidii Dieder...

In [6]:
Mycobank_api = (r'mycobank449.xlsx')
Mycobank_api_df = pd.read_excel(Mycobank_api, index_col=None)
Mycobank_api_df.set_index('id', inplace=True)
Mycobank_api_df

,name,creationDate,lastChangeDate,ownerEmail,lastChangeUserEmail,version,authors,authorsAbbreviation,ethymology,rank,...,nameStatus,mycobankNr,checkedByCurator,classification,descriptionTable,bibliographyinfo,specimeninfo,synonymy.currentNameId,synonymy.basionymId,synonymy
id,,,,,,,,,,,,,,,,,,,,,
1,Abortiporus biennis,01/01/2000,19/01/2024 14:41:33,v.robert@cbs.knaw.nl,v.robert@cbs.knaw.nl,20240119144133,(Bulliard) Singer,(Bull.) Singer,NaN,sp.,...,NaN,283905,NaN,"[0, 455206, 432186, 92345, 431129, 430993, 587...","[7012, 7293, 7351, 43855]",[],"[56206, 259295, 56207, 56208, 56209, 58036, 58...",1.0,72639.0,NaN
2,Polyporus biennis,01/01/2000,09/01/2023 10:59:58,a.decock@cbs.knaw.nl,v.robert@cbs.knaw.nl,20230109105958,(Bulliard) Fries,(Bull.) Fr.,NaN,sp.,...,NaN,191010,NaN,"[0, 455206, 432186, 92345, 431129, 430993, 587...","[7012, 7293, 7351, 43855]",[747],[],1.0,72639.0,NaN
9,Absidia anomala,01/01/2000,09/01/2023 10:41:02,a.decock@cbs.knaw.nl,v.robert@cbs.knaw.nl,20230109104102,Hesseltine & J.J. Ellis,Hesselt. & J.J. Ellis,NaN,sp.,...,NaN,325709,NaN,"[0, 455206, 566850, 452644, 431097, 452787, 92...","[7560, 7561]",[587],[5],9.0,0.0,NaN
11,Apophysomyces atrospora,01/01/2000,05/12/2023 14:18:55,a.decock@cbs.knaw.nl,v.robert@cbs.knaw.nl,20231205141855,H. Naganishi & Hirahara,H. Nagan. & Hirahara,NaN,sp.,...,Invalid,308042,NaN,"[0, 455206, 566850, 452644, 431097, 452787, 92...","[130, 131]",[38984],[30808],455866.0,0.0,NaN
13,Absidia blakesleeana,01/01/2000,22/11/2022 10:54:58,a.decock@cbs.knaw.nl,k.bensch@mycobank.org,20221122105458,Lendner,Lendn.,NaN,sp.,...,NaN,258556,NaN,"[0, 455206, 566850, 452644, 431097, 452787, 92...","[188, 189]",[31511],"[6, 178795]",455866.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614666,Umbilicaria tylorhiza,21/01/2025 11:15:37,21/01/2025 11:18:20,k.bensch@mycobank.org,k.bensch@mycobank.org,20250121111820,(Nylander) Nylander,(Nyl.) Nyl.,NaN,sp.,...,NaN,648194,NaN,"[0, 455206, 432186, 452647, 430998, 431005, 51...",[],[],[10020878],614666.0,614665.0,NaN
614667,Gyrophora tylorhiza,21/01/2025 11:19:49,21/01/2025 11:22:02,k.bensch@mycobank.org,k.bensch@mycobank.org,20250121112202,(Nylander) Nylander,(Nyl.) Nyl.,NaN,sp.,...,NaN,648195,NaN,"[0, 455206, 432186, 452647, 430998, 431005, 51...",[],[],[],614666.0,614665.0,NaN
614668,Cladonia sandstedei subsp. sandstedei,21/01/2025 11:43:33,21/01/2025 12:00:17,k.bensch@mycobank.org,k.bensch@mycobank.org,20250121120017,NaN,NaN,NaN,subsp.,...,NaN,857397,Yes,"[0, 455206, 432186, 452647, 430998, 431005, 92...",[],[],[],286047.0,286047.0,NaN
614669,Candelariella terrigena var. placodimorpha,21/01/2025 12:35:13,21/01/2025 12:39:12,k.bensch@mycobank.org,k.bensch@mycobank.org,20250121123912,Hakulinen,Hakul.,NaN,var.,...,NaN,660813,NaN,"[0, 455206, 432186, 452647, 430998, 431007, 55...",[],[],[10024484],304269.0,0.0,NaN
614670,Arthonia clemens var. clemens,21/01/2025 12:47:50,21/01/2025 12:51:35,k.bensch@mycobank.org,k.bensch@mycobank.org,20250121125135,NaN,NaN,NaN,var.,...,NaN,857398,Yes,"[0, 455206, 432186, 452647, 430998, 431047, 92...",[],[],[],152157.0,232426.0,NaN

In [13]:
combined = pd.merge(Mycobank_api_df, right=MBist_df, left_on='id', right_on='id', how='outer')
#combined.drop_duplicates(subset=['protein_accession'], inplace=True)
#combined.drop(columns=['orientation', 'location', 'gene_symbol', 'protein_name'], inplace=True)
#combined.to_csv(r'table_combined', sep ='\t', index = True) 
combined

,name_x,creationDate,lastChangeDate,ownerEmail,lastChangeUserEmail,version,authors,authorsAbbreviation,ethymology,rank,...,name_y,Authors,Rank.Rank name,Year of effective publication,Name status,MycoBank #,Hyperlink,Classification,Current name.Taxon name,Synonymy
id,,,,,,,,,,,,,,,,,,,,,
1,Abortiporus biennis,01/01/2000,19/01/2024 14:41:33,v.robert@cbs.knaw.nl,v.robert@cbs.knaw.nl,2.024012e+13,(Bulliard) Singer,(Bull.) Singer,NaN,sp.,...,Abortiporus biennis,(Bulliard) Singer,sp.,1944,Legitimate,283905.0,https://www.mycobank.org/page/Name details page/1,"Fungi, Dikarya, Basidiomycota, Agaricomycotina...",Abortiporus biennis,Current name: Abortiporus biennis (Bull.) Sing...
2,Polyporus biennis,01/01/2000,09/01/2023 10:59:58,a.decock@cbs.knaw.nl,v.robert@cbs.knaw.nl,2.023011e+13,(Bulliard) Fries,(Bull.) Fr.,NaN,sp.,...,Polyporus biennis,(Bulliard) Fries,sp.,1838,Legitimate,191010.0,https://www.mycobank.org/page/Name details page/2,"Fungi, Dikarya, Basidiomycota, Agaricomycotina...",Abortiporus biennis,Current name: Abortiporus biennis (Bull.) Sing...
9,Absidia anomala,01/01/2000,09/01/2023 10:41:02,a.decock@cbs.knaw.nl,v.robert@cbs.knaw.nl,2.023011e+13,Hesseltine & J.J. Ellis,Hesselt. & J.J. Ellis,NaN,sp.,...,Absidia anomala,Hesseltine & J.J. Ellis,sp.,1964,Legitimate,325709.0,https://www.mycobank.org/page/Name details page/9,"Fungi, Mucoromyceta, Mucoromycota, Mucoromycot...",Absidia anomala,Current name: Absidia anomala Hesselt. & J.J. ...
11,Apophysomyces atrospora,01/01/2000,05/12/2023 14:18:55,a.decock@cbs.knaw.nl,v.robert@cbs.knaw.nl,2.023121e+13,H. Naganishi & Hirahara,H. Nagan. & Hirahara,NaN,sp.,...,Apophysomyces atrospora,H. Naganishi & Hirahara,sp.,1970,Invalid,308042.0,https://www.mycobank.org/page/Name details pag...,"Fungi, Mucoromyceta, Mucoromycota, Mucoromycot...",Absidia blakesleeana var. atrospora,Current name: Lichtheimia hyalospora (Saito) K...
13,Absidia blakesleeana,01/01/2000,22/11/2022 10:54:58,a.decock@cbs.knaw.nl,k.bensch@mycobank.org,2.022112e+13,Lendner,Lendn.,NaN,sp.,...,Absidia blakesleeana,Lendner,sp.,1924,Legitimate,258556.0,https://www.mycobank.org/page/Name details pag...,"Fungi, Mucoromyceta, Mucoromycota, Mucoromycot...",Lichtheimia blakesleeana,Current name: Lichtheimia hyalospora (Saito) K...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614669,Candelariella terrigena var. placodimorpha,21/01/2025 12:35:13,21/01/2025 12:39:12,k.bensch@mycobank.org,k.bensch@mycobank.org,2.025012e+13,Hakulinen,Hakul.,NaN,var.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614670,Arthonia clemens var. clemens,21/01/2025 12:47:50,21/01/2025 12:51:35,k.bensch@mycobank.org,k.bensch@mycobank.org,2.025012e+13,NaN,NaN,NaN,var.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Licea sulphurea,Klotzsch,sp.,1839,Legitimate,164346.0,https://www.mycobank.org/page/Name details pag...,"Protozoa, Myxomycota, Myxomycetes, Liceales, L...",-,Current name: Licea sulphurea Klotzsch (1839) ...
600566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Octospora,Hedwig ex Timm,-,1788,Legitimate,92325.0,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Ascomycota, Pezizomycotina, Pe...",Octospora,"Current name: Octospora Hedw., Descriptio et a..."
415244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Peziza pixis,Linnaeus,sp.,?,Legitimate,499433.0,https://www.mycobank.org/page/Name details pag...,"Fungi, Dikarya, Ascomycota, Pezizomycotina, Pe...",Peziza pixis,Current name: Peziza pixis L. (?) [MB#499433] ...

In [11]:
Mycobank_api_df.shape

(537879, 24)

In [12]:
MBist_df.shape

(537509, 10)

In [14]:
combined.shape

(537883, 34)

In [15]:
combined.to_csv("mycobank_combined.csv")